/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedMapIndexRouteImport } from './routes/_authenticated/map/index'
import { Route as AuthenticatedLiveIndexRouteImport } from './routes/_authenticated/live/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help/index'
import { Route as AuthenticatedDevicesIndexRouteImport } from './routes/_authenticated/devices/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedAnalyticsIndexRouteImport } from './routes/_authenticated/analytics/index'
import { Route as AuthenticatedAlertsIndexRouteImport } from './routes/_authenticated/alerts/index'
import { Route as AuthenticatedForecastsRouteImport } from './routes/_authenticated/forecasts'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedReportsWeeklyRouteImport } from './routes/_authenticated/reports/weekly'
import { Route as AuthenticatedReportsMonthlyRouteImport } from './routes/_authenticated/reports/monthly'
import { Route as AuthenticatedReportsDailyRouteImport } from './routes/_authenticated/reports/daily'
import { Route as AuthenticatedReportsCustomRouteImport } from './routes/_authenticated/reports/custom'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedAnalyticsProductionRouteImport } from './routes/_authenticated/analytics/production'
import { Route as AuthenticatedAnalyticsCostRouteImport } from './routes/_authenticated/analytics/cost'
import { Route as AuthenticatedAnalyticsConsumptionRouteImport } from './routes/_authenticated/analytics/consumption'
import { Route as AuthenticatedAnalyticsCarbonFootprintRouteImport } from './routes/_authenticated/analytics/carbon-footprint'
import { Route as AuthenticatedEnergyWaterIndexRouteImport } from './routes/_authenticated/energy/water/index'
import { Route as AuthenticatedEnergySolarIndexRouteImport } from './routes/_authenticated/energy/solar/index'
import { Route as AuthenticatedEnergyGasIndexRouteImport } from './routes/_authenticated/energy/gas/index'
import { Route as AuthenticatedEnergyElectricityIndexRouteImport } from './routes/_authenticated/energy/electricity/index'
import { Route as AuthenticatedEnergyBatteryIndexRouteImport } from './routes/_authenticated/energy/battery/index'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMapIndexRoute = AuthenticatedMapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveIndexRoute = AuthenticatedLiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help/',
    path: '/help/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevicesIndexRoute =
  AuthenticatedDevicesIndexRouteImport.update({
    id: '/devices/',
    path: '/devices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlertsIndexRoute =
  AuthenticatedAlertsIndexRouteImport.update({
    id: '/alerts/',
    path: '/alerts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedForecastsRoute =
  AuthenticatedForecastsRouteImport.update({
    id: '/forecasts',
    path: '/forecasts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedReportsWeeklyRoute =
  AuthenticatedReportsWeeklyRouteImport.update({
    id: '/reports/weekly',
    path: '/reports/weekly',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsMonthlyRoute =
  AuthenticatedReportsMonthlyRouteImport.update({
    id: '/reports/monthly',
    path: '/reports/monthly',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsDailyRoute =
  AuthenticatedReportsDailyRouteImport.update({
    id: '/reports/daily',
    path: '/reports/daily',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsCustomRoute =
  AuthenticatedReportsCustomRouteImport.update({
    id: '/reports/custom',
    path: '/reports/custom',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsProductionRoute =
  AuthenticatedAnalyticsProductionRouteImport.update({
    id: '/analytics/production',
    path: '/analytics/production',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsCostRoute =
  AuthenticatedAnalyticsCostRouteImport.update({
    id: '/analytics/cost',
    path: '/analytics/cost',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsConsumptionRoute =
  AuthenticatedAnalyticsConsumptionRouteImport.update({
    id: '/analytics/consumption',
    path: '/analytics/consumption',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsCarbonFootprintRoute =
  AuthenticatedAnalyticsCarbonFootprintRouteImport.update({
    id: '/analytics/carbon-footprint',
    path: '/analytics/carbon-footprint',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnergyWaterIndexRoute =
  AuthenticatedEnergyWaterIndexRouteImport.update({
    id: '/energy/water/',
    path: '/energy/water/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnergySolarIndexRoute =
  AuthenticatedEnergySolarIndexRouteImport.update({
    id: '/energy/solar/',
    path: '/energy/solar/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnergyGasIndexRoute =
  AuthenticatedEnergyGasIndexRouteImport.update({
    id: '/energy/gas/',
    path: '/energy/gas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnergyElectricityIndexRoute =
  AuthenticatedEnergyElectricityIndexRouteImport.update({
    id: '/energy/electricity/',
    path: '/energy/electricity/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnergyBatteryIndexRoute =
  AuthenticatedEnergyBatteryIndexRouteImport.update({
    id: '/energy/battery/',
    path: '/energy/battery/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/analytics/carbon-footprint': typeof AuthenticatedAnalyticsCarbonFootprintRoute
  '/analytics/consumption': typeof AuthenticatedAnalyticsConsumptionRoute
  '/analytics/cost': typeof AuthenticatedAnalyticsCostRoute
  '/analytics/production': typeof AuthenticatedAnalyticsProductionRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/reports/custom': typeof AuthenticatedReportsCustomRoute
  '/reports/daily': typeof AuthenticatedReportsDailyRoute
  '/reports/monthly': typeof AuthenticatedReportsMonthlyRoute
  '/reports/weekly': typeof AuthenticatedReportsWeeklyRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/alerts': typeof AuthenticatedAlertsIndexRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/devices': typeof AuthenticatedDevicesIndexRoute
  '/forecasts': typeof AuthenticatedForecastsRoute
  '/help': typeof AuthenticatedHelpCenterIndexRoute
  '/live': typeof AuthenticatedLiveIndexRoute
  '/map': typeof AuthenticatedMapIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/energy/battery': typeof AuthenticatedEnergyBatteryIndexRoute
  '/energy/electricity': typeof AuthenticatedEnergyElectricityIndexRoute
  '/energy/gas': typeof AuthenticatedEnergyGasIndexRoute
  '/energy/solar': typeof AuthenticatedEnergySolarIndexRoute
  '/energy/water': typeof AuthenticatedEnergyWaterIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/analytics/carbon-footprint': typeof AuthenticatedAnalyticsCarbonFootprintRoute
  '/analytics/consumption': typeof AuthenticatedAnalyticsConsumptionRoute
  '/analytics/cost': typeof AuthenticatedAnalyticsCostRoute
  '/analytics/production': typeof AuthenticatedAnalyticsProductionRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/reports/custom': typeof AuthenticatedReportsCustomRoute
  '/reports/daily': typeof AuthenticatedReportsDailyRoute
  '/reports/monthly': typeof AuthenticatedReportsMonthlyRoute
  '/reports/weekly': typeof AuthenticatedReportsWeeklyRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/alerts': typeof AuthenticatedAlertsIndexRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/devices': typeof AuthenticatedDevicesIndexRoute
  '/forecasts': typeof AuthenticatedForecastsRoute
  '/help': typeof AuthenticatedHelpCenterIndexRoute
  '/live': typeof AuthenticatedLiveIndexRoute
  '/map': typeof AuthenticatedMapIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/energy/battery': typeof AuthenticatedEnergyBatteryIndexRoute
  '/energy/electricity': typeof AuthenticatedEnergyElectricityIndexRoute
  '/energy/gas': typeof AuthenticatedEnergyGasIndexRoute
  '/energy/solar': typeof AuthenticatedEnergySolarIndexRoute
  '/energy/water': typeof AuthenticatedEnergyWaterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/analytics/carbon-footprint': typeof AuthenticatedAnalyticsCarbonFootprintRoute
  '/_authenticated/analytics/consumption': typeof AuthenticatedAnalyticsConsumptionRoute
  '/_authenticated/analytics/cost': typeof AuthenticatedAnalyticsCostRoute
  '/_authenticated/analytics/production': typeof AuthenticatedAnalyticsProductionRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/reports/custom': typeof AuthenticatedReportsCustomRoute
  '/_authenticated/reports/daily': typeof AuthenticatedReportsDailyRoute
  '/_authenticated/reports/monthly': typeof AuthenticatedReportsMonthlyRoute
  '/_authenticated/reports/weekly': typeof AuthenticatedReportsWeeklyRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/alerts/': typeof AuthenticatedAlertsIndexRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/devices/': typeof AuthenticatedDevicesIndexRoute
  '/_authenticated/forecasts': typeof AuthenticatedForecastsRoute
  '/_authenticated/help/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/live/': typeof AuthenticatedLiveIndexRoute
  '/_authenticated/map/': typeof AuthenticatedMapIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/energy/battery/': typeof AuthenticatedEnergyBatteryIndexRoute
  '/_authenticated/energy/electricity/': typeof AuthenticatedEnergyElectricityIndexRoute
  '/_authenticated/energy/gas/': typeof AuthenticatedEnergyGasIndexRoute
  '/_authenticated/energy/solar/': typeof AuthenticatedEnergySolarIndexRoute
  '/_authenticated/energy/water/': typeof AuthenticatedEnergyWaterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/clerk'
    | '/settings'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/analytics/carbon-footprint'
    | '/analytics/consumption'
    | '/analytics/cost'
    | '/analytics/production'
    | '/errors/$error'
    | '/reports/custom'
    | '/reports/daily'
    | '/reports/monthly'
    | '/reports/weekly'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/user-management'
    | '/alerts'
    | '/analytics'
    | '/apps'
    | '/chats'
    | '/devices'
    | '/forecasts'
    | '/help'
    | '/live'
    | '/map'
    | '/reports'
    | '/settings/'
    | '/tasks'
    | '/users'
    | '/energy/battery'
    | '/energy/electricity'
    | '/energy/gas'
    | '/energy/solar'
    | '/energy/water'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/analytics/carbon-footprint'
    | '/analytics/consumption'
    | '/analytics/cost'
    | '/analytics/production'
    | '/errors/$error'
    | '/reports/custom'
    | '/reports/daily'
    | '/reports/monthly'
    | '/reports/weekly'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/user-management'
    | '/alerts'
    | '/analytics'
    | '/apps'
    | '/chats'
    | '/devices'
    | '/forecasts'
    | '/help'
    | '/live'
    | '/map'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/energy/battery'
    | '/energy/electricity'
    | '/energy/gas'
    | '/energy/solar'
    | '/energy/water'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/analytics/carbon-footprint'
    | '/_authenticated/analytics/consumption'
    | '/_authenticated/analytics/cost'
    | '/_authenticated/analytics/production'
    | '/_authenticated/errors/$error'
    | '/_authenticated/reports/custom'
    | '/_authenticated/reports/daily'
    | '/_authenticated/reports/monthly'
    | '/_authenticated/reports/weekly'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/clerk/(auth)/sign-in'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/alerts/'
    | '/_authenticated/analytics/'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/devices/'
    | '/_authenticated/forecasts'
    | '/_authenticated/help/'
    | '/_authenticated/live/'
    | '/_authenticated/map/'
    | '/_authenticated/reports/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/energy/battery/'
    | '/_authenticated/energy/electricity/'
    | '/_authenticated/energy/gas/'
    | '/_authenticated/energy/solar/'
    | '/_authenticated/energy/water/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map/': {
      id: '/_authenticated/map/'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live/': {
      id: '/_authenticated/live/'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help/': {
      id: '/_authenticated/help/'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices/': {
      id: '/_authenticated/devices/'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts/': {
      id: '/_authenticated/alerts/'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forecasts': {
      id: '/_authenticated/forecasts'
      path: '/forecasts'
      fullPath: '/forecasts'
      preLoaderRoute: typeof AuthenticatedForecastsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/reports/weekly': {
      id: '/_authenticated/reports/weekly'
      path: '/reports/weekly'
      fullPath: '/reports/weekly'
      preLoaderRoute: typeof AuthenticatedReportsWeeklyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/monthly': {
      id: '/_authenticated/reports/monthly'
      path: '/reports/monthly'
      fullPath: '/reports/monthly'
      preLoaderRoute: typeof AuthenticatedReportsMonthlyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/daily': {
      id: '/_authenticated/reports/daily'
      path: '/reports/daily'
      fullPath: '/reports/daily'
      preLoaderRoute: typeof AuthenticatedReportsDailyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/custom': {
      id: '/_authenticated/reports/custom'
      path: '/reports/custom'
      fullPath: '/reports/custom'
      preLoaderRoute: typeof AuthenticatedReportsCustomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/production': {
      id: '/_authenticated/analytics/production'
      path: '/analytics/production'
      fullPath: '/analytics/production'
      preLoaderRoute: typeof AuthenticatedAnalyticsProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/cost': {
      id: '/_authenticated/analytics/cost'
      path: '/analytics/cost'
      fullPath: '/analytics/cost'
      preLoaderRoute: typeof AuthenticatedAnalyticsCostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/consumption': {
      id: '/_authenticated/analytics/consumption'
      path: '/analytics/consumption'
      fullPath: '/analytics/consumption'
      preLoaderRoute: typeof AuthenticatedAnalyticsConsumptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/carbon-footprint': {
      id: '/_authenticated/analytics/carbon-footprint'
      path: '/analytics/carbon-footprint'
      fullPath: '/analytics/carbon-footprint'
      preLoaderRoute: typeof AuthenticatedAnalyticsCarbonFootprintRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/energy/water/': {
      id: '/_authenticated/energy/water/'
      path: '/energy/water'
      fullPath: '/energy/water'
      preLoaderRoute: typeof AuthenticatedEnergyWaterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/energy/solar/': {
      id: '/_authenticated/energy/solar/'
      path: '/energy/solar'
      fullPath: '/energy/solar'
      preLoaderRoute: typeof AuthenticatedEnergySolarIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/energy/gas/': {
      id: '/_authenticated/energy/gas/'
      path: '/energy/gas'
      fullPath: '/energy/gas'
      preLoaderRoute: typeof AuthenticatedEnergyGasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/energy/electricity/': {
      id: '/_authenticated/energy/electricity/'
      path: '/energy/electricity'
      fullPath: '/energy/electricity'
      preLoaderRoute: typeof AuthenticatedEnergyElectricityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/energy/battery/': {
      id: '/_authenticated/energy/battery/'
      path: '/energy/battery'
      fullPath: '/energy/battery'
      preLoaderRoute: typeof AuthenticatedEnergyBatteryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAnalyticsCarbonFootprintRoute: typeof AuthenticatedAnalyticsCarbonFootprintRoute
  AuthenticatedAnalyticsConsumptionRoute: typeof AuthenticatedAnalyticsConsumptionRoute
  AuthenticatedAnalyticsCostRoute: typeof AuthenticatedAnalyticsCostRoute
  AuthenticatedAnalyticsProductionRoute: typeof AuthenticatedAnalyticsProductionRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedForecastsRoute: typeof AuthenticatedForecastsRoute
  AuthenticatedReportsCustomRoute: typeof AuthenticatedReportsCustomRoute
  AuthenticatedReportsDailyRoute: typeof AuthenticatedReportsDailyRoute
  AuthenticatedReportsMonthlyRoute: typeof AuthenticatedReportsMonthlyRoute
  AuthenticatedReportsWeeklyRoute: typeof AuthenticatedReportsWeeklyRoute
  AuthenticatedAlertsIndexRoute: typeof AuthenticatedAlertsIndexRoute
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedDevicesIndexRoute: typeof AuthenticatedDevicesIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedLiveIndexRoute: typeof AuthenticatedLiveIndexRoute
  AuthenticatedMapIndexRoute: typeof AuthenticatedMapIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedEnergyBatteryIndexRoute: typeof AuthenticatedEnergyBatteryIndexRoute
  AuthenticatedEnergyElectricityIndexRoute: typeof AuthenticatedEnergyElectricityIndexRoute
  AuthenticatedEnergyGasIndexRoute: typeof AuthenticatedEnergyGasIndexRoute
  AuthenticatedEnergySolarIndexRoute: typeof AuthenticatedEnergySolarIndexRoute
  AuthenticatedEnergyWaterIndexRoute: typeof AuthenticatedEnergyWaterIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAnalyticsCarbonFootprintRoute:
    AuthenticatedAnalyticsCarbonFootprintRoute,
  AuthenticatedAnalyticsConsumptionRoute:
    AuthenticatedAnalyticsConsumptionRoute,
  AuthenticatedAnalyticsCostRoute: AuthenticatedAnalyticsCostRoute,
  AuthenticatedAnalyticsProductionRoute: AuthenticatedAnalyticsProductionRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedForecastsRoute: AuthenticatedForecastsRoute,
  AuthenticatedReportsCustomRoute: AuthenticatedReportsCustomRoute,
  AuthenticatedReportsDailyRoute: AuthenticatedReportsDailyRoute,
  AuthenticatedReportsMonthlyRoute: AuthenticatedReportsMonthlyRoute,
  AuthenticatedReportsWeeklyRoute: AuthenticatedReportsWeeklyRoute,
  AuthenticatedAlertsIndexRoute: AuthenticatedAlertsIndexRoute,
  AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedDevicesIndexRoute: AuthenticatedDevicesIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedLiveIndexRoute: AuthenticatedLiveIndexRoute,
  AuthenticatedMapIndexRoute: AuthenticatedMapIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedEnergyBatteryIndexRoute: AuthenticatedEnergyBatteryIndexRoute,
  AuthenticatedEnergyElectricityIndexRoute:
    AuthenticatedEnergyElectricityIndexRoute,
  AuthenticatedEnergyGasIndexRoute: AuthenticatedEnergyGasIndexRoute,
  AuthenticatedEnergySolarIndexRoute: AuthenticatedEnergySolarIndexRoute,
  AuthenticatedEnergyWaterIndexRoute: AuthenticatedEnergyWaterIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
